# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform:ios,'9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'BiaobeiDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
   pod 'DBXFlowTTSLib', '~> 2.2.5'
   pod 'DBASRSDKLib', '~> 1.2.2'



  # Pods for BiaobeiDemo

end
